### ISSUE TITLE
Tailwind v2

### ISSUE THREAD

**Issue by Elwood-P** [omarkhatibco/tailwind-css-variables#14]
Not working for me in Tailwind v2. Should it be?

**Comment by omarkhatibgg** [comment]
Hi @Elwood-P,

it should work, do you find a bug ?

**Comment by dnnsjsk** [comment]
Same here, no variables are being created for me.

**Comment by craigerskine** [comment]
Does this truly work for v2? Tailwind now converts your colors hex to rgba so it can be used with .bg-opacity. How can css vars even work with TWv2?

**Comment by mpalpha** [comment]
not working for v2 here either.

**Comment by craigerskine** [comment]
Just a heads up. I've since switched to [tailwindcss-theme-swapper](https://github.com/crswll/tailwindcss-theme-swapper), and it works amazingly. You have to supply your colors in RRR GGG BBB format instead of hex, but in the end it also lets you use the opacity settings on all the other components... it's so great.

Now all I need is a way to auto apply contrast forground colors for each of the `.bg-color` classes and TW will be perfect.

**Comment by mpalpha** [comment]
> Just a heads up. I've since switched to [tailwindcss-theme-swapper](https://github.com/crswll/tailwindcss-theme-swapper), and it works amazingly. You have to supply your colors in RRR GGG BBB format instead of hex, but in the end it also lets you use the opacity settings on all the other components... it's so great.
> 
> Now all I need is a way to auto apply contrast forground colors for each of the `.bg-color` classes and TW will be perfect.

Thanks, and this should get you sorted. https://gist.github.com/mpalpha/d45cdd714d2ee152a36d84fb82f00ba2

**Comment by omarkhatibgg** [comment]
Hi Everyone, 

I just rewrote it from scratch & should works again with tailwind v2.

Feel free to report any other problems.
